version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  versioning-strategy: increase
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  versioning-strategy: increase
